name: push
on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"
concurrency: push
jobs:
  build:
    strategy:
      matrix:
        GOOS:
          - linux
        GOARCH:
          - 386
          - amd64
          # - arm
          # - arm64
    uses: ./.github/workflows/build.yaml