name: push
on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"
concurrency: push
jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        GOOS: [linux]
        GOARCH: [386, amd64, arm, arm64]
    env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
      # GOMODCACHE
      - name: Get GOMODCACHE path
        id: gomodcache
        run: |
          set -e
          echo "path=$(./build.sh GOMODCACHE)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Fetch GOMODCACHE cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.gomodcache.outputs.path }}
          key: gomodcache-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-gomodcache-
      # GOCACHE
      - name: Get GOCACHE path
        id: gocache
        run: |
          set -e
          echo "path=$(./build.sh GOCACHE)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Fetch GOCACHE cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.gocache.outputs.path }}
          key: gocache-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum', '**/*.go') }}
          restore-keys: ${{ runner.os }}-gocache-
      # staticcheck
      - name: Get staticcheck cache path
        id: staticcheck
        run: |
          set -e
          # https://github.com/dominikh/go-tools/blob/cc140e9b3719aadd3b628b7a7b00523681c8b34d/lintcmd/cache/default.go#L75
          if [ "$XDG_CACHE_HOME" != "" ] ; then
            echo "path=$XDG_CACHE_HOME/staticcheck" >> $GITHUB_OUTPUT
          else
            echo "path=$HOME/.cache/staticcheck" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Fetch staticcheck cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.staticcheck.outputs.path }}
          key: staticcheck-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum', '**/*.go') }}
          restore-keys: ${{ runner.os }}-staticcheck-
      # Build
      - name: Build
        run: |
          DOCKER_PLATFORM=${{ matrix.GOOS}}/${{ matrix.GOARCH }}./build.sh ci
        shell: bash
      # Git Status
      - name: git status
        run: |
          GIT_STATUS="$(git status --porcelain)"
          if [ -n "$GIT_STATUS" ] ; then
            echo git status
            echo "$GIT_STATUS"
            echo git diff
            git diff
            exit 1
          fi
        shell: bash